version: '3.8'

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    network_mode: host
    expose:
      - 8080
  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME:0.0.0.0
    restart: always
    network_mode: host
